In [19]:
import pandas as pd
df=pd.read_csv("../data/raw/Fraudulent_E-Commerce_Transaction_Data.csv")
df2=pd.read_csv("../data/raw/Fraudulent_E-Commerce_Transaction_Data_2.csv")

checking the rows and columns

In [26]:
print(df.shape)
print(df2.shape)

(1472952, 16)
(23634, 16)

In [27]:
print(df.columns)
print(df2.columns)

Index(['Transaction ID', 'Customer ID', 'Transaction Amount',
       'Transaction Date', 'Payment Method', 'Product Category', 'Quantity',
       'Customer Age', 'Customer Location', 'Device Used', 'IP Address',
       'Shipping Address', 'Billing Address', 'Is Fraudulent',
       'Account Age Days', 'Transaction Hour'],
      dtype='str')
Index(['Transaction ID', 'Customer ID', 'Transaction Amount',
       'Transaction Date', 'Payment Method', 'Product Category', 'Quantity',
       'Customer Age', 'Customer Location', 'Device Used', 'IP Address',
       'Shipping Address', 'Billing Address', 'Is Fraudulent',
       'Account Age Days', 'Transaction Hour'],
      dtype='str')

checking data types

In [28]:
print(df.dtypes)
print(df2.dtypes)

Transaction ID            str
Customer ID               str
Transaction Amount    float64
Transaction Date          str
Payment Method            str
Product Category          str
Quantity                int64
Customer Age            int64
Customer Location         str
Device Used               str
IP Address                str
Shipping Address          str
Billing Address           str
Is Fraudulent           int64
Account Age Days        int64
Transaction Hour        int64
dtype: object
Transaction ID            str
Customer ID               str
Transaction Amount    float64
Transaction Date          str
Payment Method            str
Product Category          str
Quantity                int64
Customer Age            int64
Customer Location         str
Device Used               str
IP Address                str
Shipping Address          str
Billing Address           str
Is Fraudulent           int64
Account Age Days        int64
Transaction Hour        int64
dtype: object

checking first few rows of dataframe

In [29]:
print(df.head)
print(df2.head)

<bound method NDFrame.head of                                Transaction ID  \
0        15d2e414-8735-46fc-9e02-80b472b2580f
1        0bfee1a0-6d5e-40da-a446-d04e73b1b177
2        e588eef4-b754-468e-9d90-d0e0abfc1af0
3        4de46e52-60c3-49d9-be39-636681009789
4        074a76de-fe2d-443e-a00c-f044cdb68e21
...                                       ...
1472947  c8604004-2f4c-42ce-a1c4-cd2bebca79bb
1472948  fff0df19-fd4a-42a5-bc42-64bb7b02edb0
1472949  9e79012f-e00b-47d1-8700-0c302db20d3e
1472950  917066b1-4dfb-4472-b3f0-292663c45d21
1472951  d1a811a2-6015-47fa-95e5-0a5282755932

                                  Customer ID  Transaction Amount  \
0        d1b87f62-51b2-493b-ad6a-77e0fe13e785               58.09
1        37de64d5-e901-4a56-9ea0-af0c24c069cf              389.96
2        1bac88d6-4b22-409a-a06b-425119c57225              134.19
3        2357c76e-9253-4ceb-b44e-ef4b71cb7d4d              226.17
4        45071bc5-9588-43ea-8093-023caec8ea1c              121.53
...                                       ...                 ...
1472947  f8a534ad-0458-465e-a85b-3ad2cdf391bc              208.48
1472948  f2ef2239-d9b9-40d0-9993-4b8f305d5a7b              231.57
1472949  fa5b9a25-9606-478a-8abe-ef20bbb3980f              101.80
1472950  04524272-e14f-460b-bc70-5316bd28463d               61.80
1472951  637d5ed1-a4af-4234-a1d9-a3791b6f1bb6              376.44

            Transaction Date Payment Method Product Category  Quantity  \
0        2024-02-20 05:58:41  bank transfer      electronics         1
1        2024-02-25 08:09:45     debit card      electronics         2
2        2024-03-18 03:42:55         PayPal    home & garden         2
3        2024-03-16 20:41:31  bank transfer         clothing         5
4        2024-01-15 05:08:17  bank transfer         clothing         2
...                      ...            ...              ...       ...
1472947  2024-01-12 23:39:55         PayPal  health & beauty         2
1472948  2024-03-27 04:31:45    credit card         clothing         2
1472949  2024-01-31 23:51:42  bank transfer      electronics         4
1472950  2024-01-12 16:21:32  bank transfer      electronics         5
1472951  2024-02-19 18:57:20  bank transfer         clothing         5

         Customer Age Customer Location Device Used       IP Address  \
0                  17     Amandaborough      tablet   212.195.49.198
1                  40      East Timothy     desktop  208.106.249.121
2                  22        Davismouth      tablet     76.63.88.212
3                  31          Lynnberg     desktop   207.208.171.73
4                  51      South Nicole      tablet   190.172.14.169
...               ...               ...         ...              ...
1472947            29   North Laurafort     desktop    27.245.104.92
1472948            32        Burnsville      tablet    203.54.50.163
1472949            36        Garciafort      mobile    51.241.30.149
1472950            34   Lake Josephberg     desktop     210.67.203.4
1472951            34       Fullermouth     desktop  107.116.208.218

                                          Shipping Address  \
0                         Unit 8934 Box 0058\nDPO AA 05437
1                  634 May Keys\nPort Cherylview, NV 75063
2          16282 Dana Falls Suite 790\nRothhaven, IL 15564
3           828 Strong Loaf Apt. 646\nNew Joshua, UT 84798
4        29799 Jason Hills Apt. 439\nWest Richardtown, ...
...                                                    ...
1472947                         USNV Griffin\nFPO AA 52700
1472948    478 John Square Apt. 235\nMillerhaven, GA 68797
1472949  351 Frazier Radial Apt. 989\nPort Charles, OH ...
1472950  27307 Gonzalez Shore Suite 661\nPort Lynn, WV ...
1472951                   Unit 0520 Box 5911\nDPO AE 75554

                                           Billing Address  Is Fraudulent  \
0                         Unit 8934 Box 0058\nDPO AA 05437              0
1                  634 May Keys\nPort Cherylview, NV 75063              0
2          16282 Dana Falls Suite 790\nRothhaven, IL 15564              0
3           828 Strong Loaf Apt. 646\nNew Joshua, UT 84798              0
4        29799 Jason Hills Apt. 439\nWest Richardtown, ...              0
...                                                    ...            ...
1472947                         USNV Griffin\nFPO AA 52700              0
1472948    478 John Square Apt. 235\nMillerhaven, GA 68797              0
1472949   182 House Island Suite 198\nEast Scott, FM 84301              0
1472950  27307 Gonzalez Shore Suite 661\nPort Lynn, WV ...              0
1472951                   Unit 0520 Box 5911\nDPO AE 75554              0

         Account Age Days  Transaction Hour
0                      30                 5
1                      72                 8
2                      63                 3
3                     124                20
4                     158                 5
...                   ...               ...
1472947               149                23
1472948               132                 4
1472949                98                23
1472950               191                16
1472951               274                18

[1472952 rows x 16 columns]>
<bound method NDFrame.head of                              Transaction ID  \
0      c12e07a0-8a06-4c0d-b5cc-04f3af688570
1      7d187603-7961-4fce-9827-9698e2b6a201
2      f2c14f9d-92df-4aaf-8931-ceaf4e63ed72
3      e9949bfa-194d-486b-84da-9565fca9e5ce
4      7362837c-7538-434e-8731-0df713f5f26d
...                                     ...
23629  d8b7171f-bdd9-479c-b98b-396c621aebfe
23630  0fd12cf3-c641-4499-8de1-15dc4555cb0c
23631  649680d3-a684-44cb-95bf-9b454c3aa86d
23632  c10dbb08-28fc-4ec1-9850-d4e98d2b9640
23633  23e3c107-f2fc-48c2-abbc-7b809bf6f102

                                Customer ID  Transaction Amount  \
0      8ca9f102-02a4-4207-ab63-484e83a1bdf0               42.32
1      4d158416-caae-4b09-bd5b-15235deb9129              301.34
2      ccae47b8-75c7-4f5a-aa9e-957deced2137              340.32
3      b04960c0-aeee-4907-b1cd-4819016adcef               95.77
4      de9d6351-b3a7-4bc7-9a55-8f013eb66928               77.45
...                                     ...                 ...
23629  98a3d94c-dc9a-4525-b273-e6ffe54cc5a4               53.73
23630  b3429f52-8b27-46b5-914c-4accd989edb4               47.42
23631  066e25c9-4420-4224-bc3f-1a462708090e             1045.23
23632  cde96e9c-f562-4b8c-8fa8-f356f474232b               34.25
23633  d8d7a64e-8419-4421-910a-a7cf709a900b               85.03

          Transaction Date Payment Method Product Category  Quantity  \
0      2024-03-24 23:42:43         PayPal      electronics         1
1      2024-01-22 00:53:31    credit card      electronics         3
2      2024-01-22 08:06:03     debit card     toys & games         5
3      2024-01-16 20:34:53    credit card      electronics         5
4      2024-01-16 15:47:23    credit card         clothing         5
...                    ...            ...              ...       ...
23629  2024-01-26 16:25:05         PayPal     toys & games         5
23630  2024-02-25 17:03:26    credit card         clothing         4
23631  2024-03-28 23:46:47  bank transfer  health & beauty         1
23632  2024-02-09 11:29:18     debit card    home & garden         2
23633  2024-01-23 02:46:52    credit card         clothing         4

       Customer Age    Customer Location Device Used       IP Address  \
0                40      East Jameshaven     desktop    110.87.246.85
1                35             Kingstad      tablet    14.73.104.153
2                29           North Ryan     desktop      67.58.94.93
3                45           Kaylaville      mobile  202.122.126.216
4                42  North Edwardborough     desktop     96.77.232.76
...             ...                  ...         ...              ...
23629            32          Rebeccafurt      tablet   173.97.197.128
23630            41          Nataliefort     desktop    133.222.22.48
23631             9    East Shannonville      tablet  206.133.237.168
23632            39          Lake Nicole      mobile   16.204.137.130
23633            38             Holtport      tablet  116.188.254.162

                                        Shipping Address  \
0      5399 Rachel Stravenue Suite 718\nNorth Blakebu...
1            5230 Stephanie Forge\nCollinsbury, PR 81853
2                    195 Cole Oval\nPort Larry, IA 58422
3             7609 Cynthia Square\nWest Brenda, NV 23016
4      2494 Robert Ramp Suite 313\nRobinsonport, AS 5...
...                                                  ...
23629                         USNV Clayton\nFPO AE 82639
23630  9288 Patricia Cape Apt. 527\nMelissaton, IL 38543
23631  3015 Elizabeth Summit Suite 819\nEast Joelfort...
23632             531 Brittany Pike\nNew Stacy, OR 87952
23633           289 Adams Wells\nWest Joeltown, LA 69190

                                         Billing Address  Is Fraudulent  \
0      5399 Rachel Stravenue Suite 718\nNorth Blakebu...              0
1            5230 Stephanie Forge\nCollinsbury, PR 81853              0
2      4772 David Stravenue Apt. 447\nVelasquezside, ...              0
3             7609 Cynthia Square\nWest Brenda, NV 23016              0
4      2494 Robert Ramp Suite 313\nRobinsonport, AS 5...              0
...                                                  ...            ...
23629                         USNV Clayton\nFPO AE 82639              0
23630  9288 Patricia Cape Apt. 527\nMelissaton, IL 38543              0
23631  3015 Elizabeth Summit Suite 819\nEast Joelfort...              0
23632             531 Brittany Pike\nNew Stacy, OR 87952              0
23633           289 Adams Wells\nWest Joeltown, LA 69190              0

       Account Age Days  Transaction Hour
0                   282                23
1                   223                 0
2                   360                 8
3                   325                20
4                   116                15
...                 ...               ...
23629               363                16
23630               296                17
23631               329                23
23632               347                11
23633               203                 2

[23634 rows x 16 columns]>

checking number of missing values

In [30]:
print(df.isnull().sum())
print(df2.isnull().sum())

Transaction ID        0
Customer ID           0
Transaction Amount    0
Transaction Date      0
Payment Method        0
Product Category      0
Quantity              0
Customer Age          0
Customer Location     0
Device Used           0
IP Address            0
Shipping Address      0
Billing Address       0
Is Fraudulent         0
Account Age Days      0
Transaction Hour      0
dtype: int64
Transaction ID        0
Customer ID           0
Transaction Amount    0
Transaction Date      0
Payment Method        0
Product Category      0
Quantity              0
Customer Age          0
Customer Location     0
Device Used           0
IP Address            0
Shipping Address      0
Billing Address       0
Is Fraudulent         0
Account Age Days      0
Transaction Hour      0
dtype: int64

checking number of duplicate values

In [31]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate rows:", df2.duplicated().sum())

Duplicate rows: 0
Duplicate rows: 0

checking the data info

In [34]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1472952 entries, 0 to 1472951
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Transaction ID      1472952 non-null  str
 1   Customer ID         1472952 non-null  str
 2   Transaction Amount  1472952 non-null  float64
 3   Transaction Date    1472952 non-null  str
 4   Payment Method      1472952 non-null  str
 5   Product Category    1472952 non-null  str
 6   Quantity            1472952 non-null  int64
 7   Customer Age        1472952 non-null  int64
 8   Customer Location   1472952 non-null  str
 9   Device Used         1472952 non-null  str
 10  IP Address          1472952 non-null  str
 11  Shipping Address    1472952 non-null  str
 12  Billing Address     1472952 non-null  str
 13  Is Fraudulent       1472952 non-null  int64
 14  Account Age Days    1472952 non-null  int64
 15  Transaction Hour    1472952 non-null  int64
dtypes: float64(1), int64(5), str(10)
memory usage: 179.8 MB
None

In [35]:
print(df2.info())

<class 'pandas.DataFrame'>
RangeIndex: 23634 entries, 0 to 23633
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction ID      23634 non-null  str
 1   Customer ID         23634 non-null  str
 2   Transaction Amount  23634 non-null  float64
 3   Transaction Date    23634 non-null  str
 4   Payment Method      23634 non-null  str
 5   Product Category    23634 non-null  str
 6   Quantity            23634 non-null  int64
 7   Customer Age        23634 non-null  int64
 8   Customer Location   23634 non-null  str
 9   Device Used         23634 non-null  str
 10  IP Address          23634 non-null  str
 11  Shipping Address    23634 non-null  str
 12  Billing Address     23634 non-null  str
 13  Is Fraudulent       23634 non-null  int64
 14  Account Age Days    23634 non-null  int64
 15  Transaction Hour    23634 non-null  int64
dtypes: float64(1), int64(5), str(10)
memory usage: 2.9 MB
None

checking payment method

In [36]:
print(df["Payment Method"].value_counts())

Payment Method
credit card      368429
bank transfer    368278
debit card       368277
PayPal           367968
Name: count, dtype: int64

checking product category

In [37]:
print(df["Product Category"].value_counts())

Product Category
health & beauty    295367
electronics        295294
clothing           294319
toys & games       294266
home & garden      293706
Name: count, dtype: int64

checking which device is used

In [38]:
print(df["Device Used"].value_counts())

Device Used
mobile     491743
tablet     490938
desktop    490271
Name: count, dtype: int64

checking fraudulent transactions

In [39]:
print(df["Is Fraudulent"].value_counts())

Is Fraudulent
0    1399114
1      73838
Name: count, dtype: int64

In [40]:
df.describe()

,Transaction Amount,Quantity,Customer Age,Is Fraudulent,Account Age Days,Transaction Hour
count,1.472952e+06,1.472952e+06,1.472952e+06,1.472952e+06,1.472952e+06,1.472952e+06
mean,2.267683e+02,3.000230e+00,3.451208e+01,5.012926e-02,1.796464e+02,1.128696e+01
std,2.703951e+02,1.414736e+00,1.000313e+01,2.182117e-01,1.068642e+02,6.975995e+00
min,1.000000e+01,1.000000e+00,-1.600000e+01,0.000000e+00,1.000000e+00,0.000000e+00
25%,6.861000e+01,2.000000e+00,2.800000e+01,0.000000e+00,8.600000e+01,5.000000e+00
50%,1.517600e+02,3.000000e+00,3.500000e+01,0.000000e+00,1.790000e+02,1.100000e+01
75%,2.960500e+02,4.000000e+00,4.100000e+01,0.000000e+00,2.720000e+02,1.700000e+01
max,1.270175e+04,5.000000e+00,8.600000e+01,1.000000e+00,3.650000e+02,2.300000e+01

In [42]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1472952 entries, 0 to 1472951
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Transaction ID      1472952 non-null  str
 1   Customer ID         1472952 non-null  str
 2   Transaction Amount  1472952 non-null  float64
 3   Transaction Date    1472952 non-null  datetime64[us]
 4   Payment Method      1472952 non-null  str
 5   Product Category    1472952 non-null  str
 6   Quantity            1472952 non-null  int64
 7   Customer Age        1472952 non-null  int64
 8   Customer Location   1472952 non-null  str
 9   Device Used         1472952 non-null  str
 10  IP Address          1472952 non-null  str
 11  Shipping Address    1472952 non-null  str
 12  Billing Address     1472952 non-null  str
 13  Is Fraudulent       1472952 non-null  int64
 14  Account Age Days    1472952 non-null  int64
 15  Transaction Hour    1472952 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(5), str(9)
memory usage: 179.8 MB

In [45]:
df["Transaction Date"].isnull().sum()

np.int64(0)

In [48]:
df[df["Transaction Amount"] < 0]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour]
Index: []

In [49]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour]
Index: []

In [50]:
df[(df["Customer Age"] < 0) | (df["Customer Age"] > 100)]

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
3193,ed992d5a-4a28-45bf-bdaf-f7e737f5c8f9,4e87ec9a-7bea-4ddf-b0e6-569332c1854b,65.50,2024-02-23 20:38:18,PayPal,home & garden,1,-3,Huntburgh,tablet,99.113.154.217,USNS Brock\nFPO AP 16205,USNS Brock\nFPO AP 16205,0,229,20
7078,1fe82cb8-26a3-464c-908d-415dff80bbe4,7ff030fb-54a5-4764-8b83-108ea2b25651,61.81,2024-01-07 13:48:25,bank transfer,health & beauty,1,-4,Jasminemouth,mobile,199.127.77.116,"4850 Ingram Keys\nEast Amandafurt, WY 22396","518 Craig Parkway Suite 951\nGregoryville, RI ...",0,124,13
8213,a630b0a7-c5ee-4f0f-97f6-4aa3fc2a2d5b,ccabf552-f2ac-43c4-b723-e6bd20de72ca,411.15,2024-02-28 11:42:30,debit card,electronics,4,-4,North Courtney,tablet,37.90.116.230,"4836 Jeremy Shore\nPort Bradleyside, LA 11193","4836 Jeremy Shore\nPort Bradleyside, LA 11193",0,346,11
10110,c5a1ea50-26b3-472d-8729-acc11199bcba,020b3035-d0e9-4a3f-8bd6-a4affe5761f7,241.26,2024-03-03 01:11:29,PayPal,home & garden,3,-1,South Shaneborough,desktop,190.193.198.116,"1828 Manuel Wall Suite 113\nWebbstad, AZ 62193","94016 Hunter Cliff Suite 042\nJimenezfurt, CT ...",0,71,1
13830,6f612d29-c434-4319-bcab-698a076a4122,03121780-f53c-4aa8-ab7d-97a1482518d7,138.22,2024-02-06 19:05:39,credit card,toys & games,2,-1,Holderbury,desktop,7.110.93.93,"7311 Tara Prairie\nSouth Omarmouth, SD 42497","7311 Tara Prairie\nSouth Omarmouth, SD 42497",0,209,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444586,bf42c1ef-da0c-4f92-98e4-c8054afb1e34,c26e0a78-f0cd-404f-9bdf-ad5259238042,860.56,2024-02-29 09:01:17,bank transfer,clothing,2,-9,North Danielle,tablet,124.9.49.190,"2886 Simpson Land Suite 783\nRobinsonburgh, MO...","2886 Simpson Land Suite 783\nRobinsonburgh, MO...",0,68,9
1445037,9332dd89-50cf-4f35-a55d-0524a5f5f475,730ad608-2578-49ec-9cad-91cf3261930d,231.58,2024-01-28 17:44:18,PayPal,electronics,4,-6,Brianside,mobile,157.239.157.148,"0712 Newman Trail Suite 765\nNew Jennachester,...","0712 Newman Trail Suite 765\nNew Jennachester,...",0,252,17
1456987,9aead068-ed3f-444e-9d3d-9de0b6dc68d9,2aa3217b-0a03-440b-a18d-bbf0dadb11c6,30.75,2024-03-26 04:19:39,PayPal,clothing,3,-3,Josephport,tablet,202.246.88.140,"11440 Jesse Via Apt. 329\nVegaview, VI 49897","11440 Jesse Via Apt. 329\nVegaview, VI 49897",0,27,4
1461579,09bdead0-7df1-43ae-8437-5af84a24bdc3,230bf5c8-0516-4295-939e-83f2a4c71d38,129.69,2024-01-30 00:04:35,debit card,electronics,2,-4,New Elizabeth,desktop,205.120.55.253,"679 Megan Dale Suite 663\nNorth Kaitlynville, ...","679 Megan Dale Suite 663\nNorth Kaitlynville, ...",0,152,0
1469645,2f2ad3d5-895f-4c7c-b636-e9e61d6a42b3,1cdabd19-8d8b-4f3b-865d-bf9216334af1,103.11,2024-02-09 14:35:47,bank transfer,toys & games,3,-2,Kristieton,desktop,86.241.107.190,"03862 Emily Hill\nPaulburgh, ID 06455","03862 Emily Hill\nPaulburgh, ID 06455",0,122,14

In [ ]:
df[(df["Transaction Hour"] < 0) | (df["Transaction Hour"] > 23)]

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
3,4de46e52-60c3-49d9-be39-636681009789,2357c76e-9253-4ceb-b44e-ef4b71cb7d4d,226.17,2024-03-16 20:41:31,bank transfer,clothing,5,31,Lynnberg,desktop,207.208.171.73,"828 Strong Loaf Apt. 646\nNew Joshua, UT 84798","828 Strong Loaf Apt. 646\nNew Joshua, UT 84798",0,124,20
6,7ed952fe-8ae1-4f11-8cc5-6607060240d8,fe21ae29-ba4c-424f-9d55-0095539c09fa,92.88,2024-02-04 19:59:10,PayPal,toys & games,2,14,Ramosfort,tablet,13.45.27.192,"727 Gibson Islands Apt. 279\nNew Davidbury, ME...","727 Gibson Islands Apt. 279\nNew Davidbury, ME...",0,119,19
7,0b2fb5aa-7171-472f-8269-371094608a07,024257c3-5671-4de8-a33c-98fc5cbe6f92,318.14,2024-02-20 13:30:29,credit card,health & beauty,4,42,Port Emily,desktop,131.141.230.185,"3914 Davis Union\nBrownchester, IN 07744","3914 Davis Union\nBrownchester, IN 07744",0,251,13
8,1f52366c-7f40-4397-885f-3856b6e6531c,f17640ca-49da-45d1-8461-c2a1cf9c1b61,47.92,2024-03-03 19:44:00,bank transfer,home & garden,4,38,Carneyfurt,desktop,210.148.17.240,"47893 Maldonado Stream Suite 443\nBrownshire, ...","47893 Maldonado Stream Suite 443\nBrownshire, ...",0,190,19
9,3f10dfde-9c4c-4085-9872-4f6b39502ffb,aab93e75-582f-4455-80b4-1fb35733a47c,121.78,2024-01-16 21:19:39,bank transfer,health & beauty,4,39,Brockburgh,mobile,174.32.252.238,"2334 Briana Centers Suite 576\nArchershire, NM...","2334 Briana Centers Suite 576\nArchershire, NM...",0,343,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472943,5d5b71f3-543a-4728-94d7-1265c9b27fec,6a30b559-5722-4711-868a-9a2b07346631,23.69,2024-02-25 20:26:35,credit card,toys & games,4,49,Emmafurt,desktop,31.89.225.1,843 Katherine Curve Suite 279\nLake Laurenburg...,843 Katherine Curve Suite 279\nLake Laurenburg...,0,318,20
1472947,c8604004-2f4c-42ce-a1c4-cd2bebca79bb,f8a534ad-0458-465e-a85b-3ad2cdf391bc,208.48,2024-01-12 23:39:55,PayPal,health & beauty,2,29,North Laurafort,desktop,27.245.104.92,USNV Griffin\nFPO AA 52700,USNV Griffin\nFPO AA 52700,0,149,23
1472949,9e79012f-e00b-47d1-8700-0c302db20d3e,fa5b9a25-9606-478a-8abe-ef20bbb3980f,101.80,2024-01-31 23:51:42,bank transfer,electronics,4,36,Garciafort,mobile,51.241.30.149,"351 Frazier Radial Apt. 989\nPort Charles, OH ...","182 House Island Suite 198\nEast Scott, FM 84301",0,98,23
1472950,917066b1-4dfb-4472-b3f0-292663c45d21,04524272-e14f-460b-bc70-5316bd28463d,61.80,2024-01-12 16:21:32,bank transfer,electronics,5,34,Lake Josephberg,desktop,210.67.203.4,"27307 Gonzalez Shore Suite 661\nPort Lynn, WV ...","27307 Gonzalez Shore Suite 661\nPort Lynn, WV ...",0,191,16
1472951,d1a811a2-6015-47fa-95e5-0a5282755932,637d5ed1-a4af-4234-a1d9-a3791b6f1bb6,376.44,2024-02-19 18:57:20,bank transfer,clothing,5,34,Fullermouth,desktop,107.116.208.218,Unit 0520 Box 5911\nDPO AE 75554,Unit 0520 Box 5911\nDPO AE 75554,0,274,18

In [54]:
df[df["Account Age Days"] < 0]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour]
Index: []

In [56]:
print(df["Shipping Address"].iloc[0])

Unit 8934 Box 0058
DPO AA 05437

In [57]:
df["Shipping Address"] = (
    df["Shipping Address"]
    .str.replace("\n", " ", regex=False)
    .str.strip()
)

In [58]:
df["Billing Address"] = (
    df["Billing Address"]
    .str.replace("\n", " ", regex=False)
    .str.strip()
)

In [59]:
text_columns = [
    "Payment Method",
    "Product Category",
    "Customer Location",
    "Device Used"
]

for col in text_columns:
    df[col] = df[col].str.strip().str.lower()

In [60]:
for col in text_columns:
    print("\n", col)
    print(df[col].unique())

 Payment Method
<StringArray>
['bank transfer', 'debit card', 'paypal', 'credit card']
Length: 4, dtype: str

 Product Category
<StringArray>
['electronics', 'home & garden', 'clothing', 'toys & games',
 'health & beauty']
Length: 5, dtype: str

 Customer Location
<StringArray>
[     'amandaborough',       'east timothy',         'davismouth',
           'lynnberg',       'south nicole',       'herreramouth',
          'ramosfort',         'port emily',         'carneyfurt',
         'brockburgh',
 ...
   'port alisonhaven',   'lake haydenmouth', 'south glennborough',
    'lake marciaberg',   'north mariehaven',   'lake jeanborough',
   'north jeromeport',    'west peggyshire',        'new maxfort',
  'south melvinburgh']
Length: 99135, dtype: str

 Device Used
<StringArray>
['tablet', 'desktop', 'mobile']
Length: 3, dtype: str

In [61]:
import ipaddress

def valid_ip(ip):
    try:
        ipaddress.ip_address(ip)
        return True
    except:
        return False

df["Valid IP"] = df["IP Address"].apply(valid_ip)

df["Valid IP"].value_counts()

Valid IP
True    1472952
Name: count, dtype: int64

In [62]:
df.drop(columns=["Valid IP"], inplace=True)

Checking sipping address is as same as billing address

In [63]:
df["Address Mismatch"] = (
    df["Shipping Address"] != df["Billing Address"]
)
df["Address Mismatch"].value_counts()

Address Mismatch
False    1325429
True      147523
Name: count, dtype: int64

In [64]:

df["Calculated Hour"] = df["Transaction Date"].dt.hour

In [65]:
(df["Calculated Hour"] != df["Transaction Hour"]).sum()

np.int64(28480)

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
df["Transaction ID"].duplicated().sum()

np.int64(0)

In [68]:
df[df["Transaction ID"].duplicated(keep=False)].sort_values("Transaction ID")

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour, Address Mismatch, Calculated Hour]
Index: []

In [69]:
df["Is Fraudulent"].value_counts()

Is Fraudulent
0    1399114
1      73838
Name: count, dtype: int64

In [70]:
df["Is Fraudulent"].value_counts(normalize=True) * 100

Is Fraudulent
0    94.987074
1     5.012926
Name: proportion, dtype: float64

In [71]:
(df["Customer Age"] < 0).sum()

np.int64(258)

In [72]:
df.loc[df["Customer Age"] < 0, "Customer Age"] = pd.NA

In [73]:
median_age = df["Customer Age"].median()

In [74]:
df["Customer Age"] = df["Customer Age"].fillna(median_age)